site_name: "box"

theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - navigation.footer
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

site_url: https://box.readthedocs.io
repo_url: https://github.com/trappitsch/box
site_author: Reto Trappitsch

markdown_extensions:
  - admonition
  - mkdocs-click
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true


plugins:
  - search
  - include-markdown:
      preserve_includer_indent: true


nav:
  - Home: index.md
  - CLI: cli.md
  - Usage guide: guide.md
  - Changelog: changelog.md
  - Examples: examples.md
  - Tips: tips.md
