name: integration_tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MAIN_PYTHON_VERSION: "3.12"

jobs:
  integration_tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout box
      uses: actions/checkout@v4
    - name: Install python and setup project
      uses: actions/setup-python@v5
      with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
    - name: pip install
      run: |
        pip install .
        pip install build
    - name: Checkout qtcowsay
      uses: actions/checkout@v4
      with:
        repository: trappitsch/qtcowsay
        path: "qtcowsay"
    - name: Test build qtcowsay (GUI)
      run: |
        cd qtcowsay
        box init -q -b build
        box package
        box installer
    - name: Checkout cowsay-python
      uses: actions/checkout@v4
      with:
          repository: VaasuDevanS/cowsay-python
          path: "cowsay"
    - name: Test build cowsay-python (CLI)
      run: |
        cd cowsay
        git checkout 3db622cefd8b11620ece7386d4151b5e734b078b
        box init -q -b build
        box package
        box installer
