name: Release creation

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  PYTHON_VERSION: "3.12"

jobs:
  build-linux:
    name: Release on PyPi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Sync Rye
        run: |
          rye pin ${{ env.PYTHON_VERSION }}
          rye sync
      - name: Build and release the controller
        run: |
          rye build
          rye publish --token ${{ secrets.PYPI_TOKEN }} --yes
