# Release on PyPi if a realease is created

name: Release on PyPi

on:
  release:
    types: [created]

env:
  PYTHON_VERSION: "3.12"

jobs:
  deploy:
    if: github.repository_owner == 'trappitsch'
    name: Release on PyPi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Sync Rye
        run: |
          rye pin ${{ env.PYTHON_VERSION }}
          rye sync
      - name: Build and release the controller
        run: |
          rye build
          rye publish --token ${{ secrets.PYPI_TOKEN }} --yes
