name: unittests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MAIN_PYTHON_VERSION: "3.12"

jobs:
  # Build and test
  strategy:
    matrix:
      os: [ubuntu-latest, macos-latest, windows-latest]
  unit-tests:
    runs-on: {{matrix.os }}
    steps:
    - name: Checkout box
      uses: actions/checkout@v4
      with:
        path: "box"
    - name: Install python and setup project
      uses: actions/setup-python@v5
      with:
          python-version: env.MAIN_PYTHON_VERSION
    - name: Pip install
      run: |
        pip install box
        pip install build
    - name: Checkout qtcowsay
      uses: actions/check-run-action@v4
      with:
        repository: trappitsch/qtcowsay
        path: "qtcowsay"
    - name: Test build qtcowsay (GUI)
      run: |
        cd qtcowsay
        box init -q -b build
        box package
    - name: Checkout cowsay-python
      uses: actions/check-run-action@v4
      with:
          repository: VassuDevanS/cowsay-python
          path: "cowsay"
    - name: Test build cowsay-python (CLI)
      run: |
          git checkout 3db622cefd8b11620ece7386d4151b5e734b078b
          cd cowsay
          box init -q -b build
          box package
